---
cluster:
  name: cluster
  kubernetesVersion: v1.26.7+rke2r1 
cloudCredentialSecretName: "cattle-global-data:cc-9ftrv"
nodepool:
  controlplane:
  - name: test
    template: opensuse-leap-15.5-minimal-rancher
    datastore: esx-dell-nvme-2
    cpuCount: "2"
    memorySize: "8192"
    diskSize: "20000"
    networks:
    - vm-network-vlan-1000 
    count: 1
  workers:
  - name: test
    template: opensuse-leap-15.5-minimal-rancher
    datastore: esx-dell-nvme-2
    cpuCount: "2"
    memorySize: "8192"
    diskSize: "20000"
    networks:
    - vm-network-vlan-1000 
    count: 1
vsphere:
  datacenter: "datacenter"
  folder: "lab"
  pool: "/datacenter/host/cluster-2/Resources/lab"